Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/09/2023
Var
   contador : inteiro


Inicio
   para contador <- 1 ate 100 faca
      se(contador % 10 = 0) entao
         escreval(contador," esse cara é multiplo de 10")
      senao
         escreval(contador)
      fimSe
   fimPara

Fimalgoritmo