Algoritmo "correção 1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/09/2023
Var
numero : inteiro

Inicio
escreva("Digite um número para visualizar o antecessor: ")
leia(numero)

escreval("O antecessor do número é : ",numero - 1)

Fimalgoritmo